/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as PlanPickerRouteImport } from './routes/plan-picker'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthVerifiedRouteImport } from './routes/auth.verified'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanPickerRoute = PlanPickerRouteImport.update({
  id: '/plan-picker',
  path: '/plan-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifiedRoute = AuthVerifiedRouteImport.update({
  id: '/auth/verified',
  path: '/auth/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/careers': typeof CareersRoute
  '/download': typeof DownloadRoute
  '/dpa': typeof DpaRoute
  '/extension': typeof ExtensionRoute
  '/onboarding': typeof OnboardingRoute
  '/plan-picker': typeof PlanPickerRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/auth/verify': typeof AuthVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/careers': typeof CareersRoute
  '/download': typeof DownloadRoute
  '/dpa': typeof DpaRoute
  '/extension': typeof ExtensionRoute
  '/onboarding': typeof OnboardingRoute
  '/plan-picker': typeof PlanPickerRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/auth/verify': typeof AuthVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/careers': typeof CareersRoute
  '/download': typeof DownloadRoute
  '/dpa': typeof DpaRoute
  '/extension': typeof ExtensionRoute
  '/onboarding': typeof OnboardingRoute
  '/plan-picker': typeof PlanPickerRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/auth/verify': typeof AuthVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/careers'
    | '/download'
    | '/dpa'
    | '/extension'
    | '/onboarding'
    | '/plan-picker'
    | '/press'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/auth/forgot'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verified'
    | '/auth/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/careers'
    | '/download'
    | '/dpa'
    | '/extension'
    | '/onboarding'
    | '/plan-picker'
    | '/press'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/auth/forgot'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verified'
    | '/auth/verify'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/careers'
    | '/download'
    | '/dpa'
    | '/extension'
    | '/onboarding'
    | '/plan-picker'
    | '/press'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/auth/forgot'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verified'
    | '/auth/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  CareersRoute: typeof CareersRoute
  DownloadRoute: typeof DownloadRoute
  DpaRoute: typeof DpaRoute
  ExtensionRoute: typeof ExtensionRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanPickerRoute: typeof PlanPickerRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifiedRoute: typeof AuthVerifiedRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-picker': {
      id: '/plan-picker'
      path: '/plan-picker'
      fullPath: '/plan-picker'
      preLoaderRoute: typeof PlanPickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verified': {
      id: '/auth/verified'
      path: '/auth/verified'
      fullPath: '/auth/verified'
      preLoaderRoute: typeof AuthVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  CareersRoute: CareersRoute,
  DownloadRoute: DownloadRoute,
  DpaRoute: DpaRoute,
  ExtensionRoute: ExtensionRoute,
  OnboardingRoute: OnboardingRoute,
  PlanPickerRoute: PlanPickerRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifiedRoute: AuthVerifiedRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
